/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sri.kkp.view;

import com.sri.kkp.contoller.UserController;
import java.awt.CardLayout;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author KNO1300457
 */
public class App extends javax.swing.JFrame {
    
    private PanelPelanggan panelPelanggan;
    private PanelProgram panelProgram;
    private PanelPerusahaan panelPerusahaan;
    private UserController userController;
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        setLocationRelativeTo(null);
        menuPelanggan.setEnabled(false);
        menuPerusahaan.setEnabled(false);
        menuProgram.setEnabled(false);
        
        // Controller
        userController = new UserController();
        
        // Add panel pelanggan
        panelPelanggan = new PanelPelanggan();
        mainPanel.add("panelPelanggan", panelPelanggan);
        
        // Add panel program
        panelProgram = new PanelProgram();
        mainPanel.add("panelProgram", panelProgram);
        
        // Add panel Perusahaan
        panelPerusahaan = new PanelPerusahaan();
        mainPanel.add("panelPerusahaan", panelPerusahaan);
    }

    public JPasswordField getTextPassword() {
        return textPassword;
    }

    public JTextField getTextUsername() {
        return textUsername;
    }

    public JMenu getMenuPelanggan() {
        return menuPelanggan;
    }

    public JMenu getMenuPerusahaan() {
        return menuPerusahaan;
    }

    public JMenu getMenuProgram() {
        return menuProgram;
    }

    public PanelPelanggan getPanelPelanggan() {
        return panelPelanggan;
    }

    public PanelProgram getPanelProgram() {
        return panelProgram;
    }

    public PanelPerusahaan getPanelPerusahaan() {
        return panelPerusahaan;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        labelPerusahaan = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelKeterangan = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        mainMenu = new javax.swing.JMenuBar();
        menuPerusahaan = new javax.swing.JMenu();
        menuItemPerusahaanInput = new javax.swing.JMenuItem();
        menuPelanggan = new javax.swing.JMenu();
        menuItemPelangganInput = new javax.swing.JMenuItem();
        menuProgram = new javax.swing.JMenu();
        menuItemProgramInput = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 525));
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        labelPerusahaan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPerusahaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPerusahaan.setText("PT INTIPESAN PARIWARA");

        labelUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelUsername.setText("Username :");

        labelPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPassword.setText("Password :");

        labelKeterangan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKeterangan.setText("SILAHKAN LOGIN");

        textUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKeterangan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPerusahaan, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPassword)
                            .addComponent(textUsername)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelPerusahaan)
                .addGap(18, 18, 18)
                .addComponent(labelKeterangan)
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername)
                    .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonLogin)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        mainPanel.add(panelLogin, "card2");

        menuPerusahaan.setText("Perusahaan");

        menuItemPerusahaanInput.setText("Input Perusahaan");
        menuItemPerusahaanInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPerusahaanInputActionPerformed(evt);
            }
        });
        menuPerusahaan.add(menuItemPerusahaanInput);

        mainMenu.add(menuPerusahaan);

        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });

        menuItemPelangganInput.setText("Input Pelanggan");
        menuItemPelangganInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPelangganInputActionPerformed(evt);
            }
        });
        menuPelanggan.add(menuItemPelangganInput);

        mainMenu.add(menuPelanggan);

        menuProgram.setText("Program");

        menuItemProgramInput.setText("Input Program");
        menuItemProgramInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProgramInputActionPerformed(evt);
            }
        });
        menuProgram.add(menuItemProgramInput);

        mainMenu.add(menuProgram);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPerusahaanInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPerusahaanInputActionPerformed
        // TODO add your handling code here:
        showPanel("panelPerusahaan");
    }//GEN-LAST:event_menuItemPerusahaanInputActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void menuItemPelangganInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPelangganInputActionPerformed
        // TODO add your handling code here:
        showPanel("panelPelanggan");
    }//GEN-LAST:event_menuItemPelangganInputActionPerformed

    private void menuItemProgramInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProgramInputActionPerformed
        // TODO add your handling code here:
        showPanel("panelProgram");
    }//GEN-LAST:event_menuItemProgramInputActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        userController.loginController(this);
    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel labelKeterangan;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPerusahaan;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem menuItemPelangganInput;
    private javax.swing.JMenuItem menuItemPerusahaanInput;
    private javax.swing.JMenuItem menuItemProgramInput;
    private javax.swing.JMenu menuPelanggan;
    private javax.swing.JMenu menuPerusahaan;
    private javax.swing.JMenu menuProgram;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables

    public void showPanel(String panelIdentifier){
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, panelIdentifier);
    }
}
