/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sri.kkp.view;

/**
 *
 * @author KNO1300457
 */
public class PanelProgram extends javax.swing.JPanel {

    /**
     * Creates new form PanelPelanggan
     */
    public PanelProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelKodeProgram = new javax.swing.JLabel();
        labelJenisProgram = new javax.swing.JLabel();
        labelJudulProgram = new javax.swing.JLabel();
        textKodeProgram = new javax.swing.JTextField();
        textJenisProgram = new javax.swing.JTextField();
        comboSeminar = new javax.swing.JComboBox();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        labelKodeProgram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKodeProgram.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKodeProgram.setText("Kode Program :");

        labelJenisProgram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJenisProgram.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelJenisProgram.setText("Jenis Program :");

        labelJudulProgram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudulProgram.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelJudulProgram.setText("Judul Program :");

        textKodeProgram.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textJenisProgram.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        comboSeminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboSeminar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEMINAR", "TRAINING" }));

        buttonSave.setText("Save");

        buttonCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelJenisProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelKodeProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelJudulProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textJenisProgram)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textKodeProgram, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(comboSeminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 198, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSave)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeProgram)
                    .addComponent(textKodeProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJenisProgram)
                    .addComponent(comboSeminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJudulProgram)
                    .addComponent(textJenisProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave)
                    .addComponent(buttonCancel))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox comboSeminar;
    private javax.swing.JLabel labelJenisProgram;
    private javax.swing.JLabel labelJudulProgram;
    private javax.swing.JLabel labelKodeProgram;
    private javax.swing.JTextField textJenisProgram;
    private javax.swing.JTextField textKodeProgram;
    // End of variables declaration//GEN-END:variables
}
