/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sri.kkp.view;

import com.sri.kkp.contoller.PerusahaanController;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author KNO1300457
 */
public class PanelPerusahaan extends javax.swing.JPanel {

    private PerusahaanController controller;
    
    /**
     * Creates new form PanelPerusahaan
     */
    public PanelPerusahaan() {
        initComponents();
        controller = new PerusahaanController();
    }

    public JComboBox getComboJenisUsaha() {
        return comboJenisUsaha;
    }

    public JComboBox getComboSumberData() {
        return comboSumberData;
    }

    public JLabel getLabelSumberData() {
        return labelSumberData;
    }

    public JTextArea getTextAreaAlamat() {
        return textAreaAlamat;
    }

    public JTextField getTextJenisUsaha() {
        return textJenisUsaha;
    }

    public JTextField getTextKodePerusahaan() {
        return textKodePerusahaan;
    }

    public JTextField getTextKodePos() {
        return textKodePos;
    }

    public JTextField getTextKota() {
        return textKota;
    }

    public JTextField getTextNamaPerusahaan() {
        return textNamaPerusahaan;
    }

    public JFormattedTextField getTextNomorFax() {
        return textNomorFax;
    }

    public JFormattedTextField getTextNomorTelp() {
        return textNomorTelp;
    }

    public JTextField getTextSumberData() {
        return textSumberData;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelKodePerusahaan = new javax.swing.JLabel();
        labelNamaPerusahaan = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelKota = new javax.swing.JLabel();
        labelNomorTelp = new javax.swing.JLabel();
        labelSumberData = new javax.swing.JLabel();
        labelJenisUsaha = new javax.swing.JLabel();
        labelKodePos = new javax.swing.JLabel();
        labelNomorFax = new javax.swing.JLabel();
        textKodePerusahaan = new javax.swing.JTextField();
        textNamaPerusahaan = new javax.swing.JTextField();
        textKota = new javax.swing.JTextField();
        textKodePos = new javax.swing.JTextField();
        textSumberData = new javax.swing.JTextField();
        textJenisUsaha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaAlamat = new javax.swing.JTextArea();
        comboSumberData = new javax.swing.JComboBox();
        comboJenisUsaha = new javax.swing.JComboBox();
        buttonCancel = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        textNomorFax = new javax.swing.JFormattedTextField();
        textNomorTelp = new javax.swing.JFormattedTextField();

        labelKodePerusahaan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKodePerusahaan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKodePerusahaan.setText("Kode Perusahaan :");

        labelNamaPerusahaan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNamaPerusahaan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNamaPerusahaan.setText("Nama Perusahaan :");

        labelAlamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelAlamat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAlamat.setText("Alamat Perusahaan :");

        labelKota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKota.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKota.setText("Kota :");

        labelNomorTelp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNomorTelp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNomorTelp.setText("Nomor Telp. :");

        labelSumberData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSumberData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSumberData.setText("Sumber Data :");

        labelJenisUsaha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJenisUsaha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelJenisUsaha.setText("Jenis Usaha :");

        labelKodePos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKodePos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKodePos.setText("Kode Pos :");

        labelNomorFax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNomorFax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNomorFax.setText("Nomor Fax :");

        textKodePerusahaan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textNamaPerusahaan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textKota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textKodePos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textSumberData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textJenisUsaha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textAreaAlamat.setColumns(20);
        textAreaAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textAreaAlamat.setRows(5);
        jScrollPane1.setViewportView(textAreaAlamat);

        comboSumberData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Peserta", "Koran", "Iklan", "Internet" }));

        comboJenisUsaha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oil & Gas", "Bank", "Asuransi", "Ritel" }));

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        textNomorFax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textNomorFax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textNomorTelp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textNomorTelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelKodePerusahaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNamaPerusahaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelKota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNomorTelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSumberData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelJenisUsaha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(textNamaPerusahaan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboSumberData, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textKodePerusahaan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textKota, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboJenisUsaha, 0, 132, Short.MAX_VALUE)
                                    .addComponent(textNomorTelp))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(labelKodePos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelNomorFax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textKodePos, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                            .addComponent(textNomorFax)))
                                    .addComponent(textSumberData)
                                    .addComponent(textJenisUsaha)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSave)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodePerusahaan)
                    .addComponent(textKodePerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaPerusahaan)
                    .addComponent(textNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKota)
                    .addComponent(textKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKodePos)
                    .addComponent(textKodePos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomorTelp)
                    .addComponent(labelNomorFax)
                    .addComponent(textNomorFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNomorTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSumberData)
                    .addComponent(comboSumberData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSumberData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJenisUsaha)
                    .addComponent(textJenisUsaha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboJenisUsaha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        controller.inputPerusahaan(this);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        controller.cancel(this);
    }//GEN-LAST:event_buttonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox comboJenisUsaha;
    private javax.swing.JComboBox comboSumberData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelJenisUsaha;
    private javax.swing.JLabel labelKodePerusahaan;
    private javax.swing.JLabel labelKodePos;
    private javax.swing.JLabel labelKota;
    private javax.swing.JLabel labelNamaPerusahaan;
    private javax.swing.JLabel labelNomorFax;
    private javax.swing.JLabel labelNomorTelp;
    private javax.swing.JLabel labelSumberData;
    private javax.swing.JTextArea textAreaAlamat;
    private javax.swing.JTextField textJenisUsaha;
    private javax.swing.JTextField textKodePerusahaan;
    private javax.swing.JTextField textKodePos;
    private javax.swing.JTextField textKota;
    private javax.swing.JTextField textNamaPerusahaan;
    private javax.swing.JFormattedTextField textNomorFax;
    private javax.swing.JFormattedTextField textNomorTelp;
    private javax.swing.JTextField textSumberData;
    // End of variables declaration//GEN-END:variables
}
